name: Zephyr CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ZEPHYR_BASE: ${{ github.workspace }}/zephyr
    steps:
    - name: Checkout your repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build gperf python3-pip python3-setuptools \
                            python3-wheel xz-utils file make gcc gcc-multilib \
                            libncurses-dev libffi-dev git wget
        sudo apt install gcc-arm-none-eabi
        pip3 install west
        pip3 install -r zephyr/scripts/requirements.txt

    - name: Build Zephyr sample using west
      run: |
        source zephyr/zephyr-env.sh
        west build  ./zephyr/samples/hello_world -b qemu_cortex_m3

    - name: Run Pytest on QEMU
      run: |
        source zephyr/zephyr-env.sh
        pytest zephyr/pytest-tests/ -s