name: Zephyr CI Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.24.5
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev python3-setuptools python3-wheel \
            xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev

      - name: Install west and Python deps
        run: |
          pip3 install -U west
          pip3 install -r zephyr/scripts/requirements.txt

      - name: Build hello_world for QEMU
        run: |
          source zephyr/zephyr-env.sh
          west build -b qemu_x86 zephyr/samples/hello_world
          pytest ./zephyr/pytest-tests/pytest-reference.py -s