name: Zephyr CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build gperf python3-pip python3-setuptools \
                            python3-wheel xz-utils file make gcc gcc-multilib \
                            libncurses-dev libffi-dev git wget

    - name: Install west and Python deps
      run: |
        pip3 install west
        west init -l .
        west update
        west zephyr-export
        pip3 install -r zephyr/scripts/requirements.txt

    - name: Install Zephyr SDK
      run: |
        wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_linux-x86_64.tar.xz
        tar xf zephyr-sdk-0.16.4_linux-x86_64.tar.xz
        mv zephyr-sdk-0.16.4 $HOME/zephyr-sdk
        $HOME/zephyr-sdk/setup.sh -t all -h -y
      env:
        ZEPHYR_SDK_INSTALL_DIR: $HOME/zephyr-sdk

    - name: Build with west
      run: |
        export ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk
        west build -b your_board_name path/to/your/app
