name: Zephyr CI Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.24.5
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install west and Python deps
        run: |
          rm -rf .west
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Export Zephyr environment
        run: |
          unset ZEPHYR_BASE
          source zephyr/zephyr-env.sh

      - name: Build hello_world for QEMU
        run: |
          west build -b qemu_x86 zephyr/samples/hello_world
          pytest ./zephyr/pytest-tests/pytest-reference.py -s