# .github/workflows/build.yml
name: Build Zephyr Application

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.25.4
      options: --user root  # Optional: run as root if needed

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Init west
      run: |
        west init -l .
        west update
        west zephyr-export
        pip3 install -r zephyr/scripts/requirements.txt

    - name: Build project
      run: |
        west build -b qemu_cortex_m3 zephyr/samples/hello_world
