name: Zephyr CI Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.24.5
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev python3-setuptools python3-wheel \
            xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev
          sudo apt-get install -y qemu-system-arm

      - name: Set up Python 3.13.0
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'

      - name: Install west and Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -U west
          pip install -r zephyr/scripts/requirements.txt
          pip install pynmea2

      - name: Build hello_world for QEMU
        shell: bash
        run: |
          source zephyr/zephyr-env.sh
          pytest ./zephyr/pytest-tests/modem-test.py -s